name: openHAB Static Analysis (Java 21)

on:
  pull_request:
    branches: [ main, PR-warnings ]
  workflow_dispatch:

jobs:
  analyze:
    name: Check New Warnings
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Viktig for at Reviewdog skal kunne sammenligne diff

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and match
        # Vi kjører compile først for å sikre at SpotBugs har bytecode å analysere
        run: | 
          echo "::add-matcher::.github/maven-matcher.json"
          mvn clean compile -DskipTests -B -pl :org.openhab.binding.enocean
